#!/bin/bash

# WhatsApp AI - Interactive Setup Script
# For macOS

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m' # No Color

# Print functions
print_banner() {
    echo ""
    echo -e "${BOLD}${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║       WhatsApp AI Setup Wizard         ║${NC}"
    echo -e "${BOLD}${GREEN}╚════════════════════════════════════════╝${NC}"
    echo ""
}

print_step() {
    echo -e "${CYAN}→${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Main setup
main() {
    print_banner

    # Check Node.js
    print_step "Checking Node.js..."
    if ! command_exists node; then
        print_error "Node.js is not installed"
        echo ""
        echo "Install Node.js 20+ using one of these methods:"
        echo ""
        echo "  Using Homebrew:"
        echo "    brew install node@20"
        echo ""
        echo "  Using nvm:"
        echo "    nvm install 20"
        echo ""
        echo "  Download from:"
        echo "    https://nodejs.org/"
        echo ""
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 20 ]; then
        print_error "Node.js 20+ required (found v$NODE_VERSION)"
        exit 1
    fi
    print_success "Node.js v$(node -v | cut -d'v' -f2) found"

    # Check npm
    print_step "Checking npm..."
    if ! command_exists npm; then
        print_error "npm is not installed"
        exit 1
    fi
    print_success "npm v$(npm -v) found"

    # Install dependencies
    echo ""
    print_step "Installing dependencies..."
    npm install --silent
    print_success "Dependencies installed"

    # Build TypeScript
    print_step "Building TypeScript..."
    npm run build --silent
    print_success "Build complete"

    # Setup .env file
    echo ""
    if [ -f ".env" ]; then
        print_info ".env file already exists"
        read -p "Do you want to reconfigure it? (y/N) " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Keeping existing configuration"
            setup_complete
            return
        fi
    fi

    echo ""
    echo -e "${BOLD}Configuration${NC}"
    echo -e "${DIM}The passphrase encrypts your WhatsApp credentials stored locally.${NC}"
    echo -e "${DIM}Choose something memorable - you'll need it if you restart the server.${NC}"
    echo ""

    # Get passphrase
    while true; do
        read -sp "Enter passphrase (min 8 characters): " PASSPHRASE
        echo ""
        
        if [ ${#PASSPHRASE} -lt 8 ]; then
            print_error "Passphrase must be at least 8 characters"
            continue
        fi

        read -sp "Confirm passphrase: " PASSPHRASE_CONFIRM
        echo ""

        if [ "$PASSPHRASE" != "$PASSPHRASE_CONFIRM" ]; then
            print_error "Passphrases don't match"
            continue
        fi

        break
    done

    # Create .env file
    cat > .env << EOF
# WhatsApp MCP Server Configuration
# Generated by setup.sh

WHATSAPP_PASSPHRASE=$PASSPHRASE

# Optional settings (uncomment to customize)
# WHATSAPP_STORE_PATH=./store
# WHATSAPP_REQUIRE_CONFIRMATION=true
# WHATSAPP_MAX_MESSAGES=50
# WHATSAPP_MAX_CHATS=100
# WHATSAPP_RATE_LIMIT=60
# WHATSAPP_LOG_LEVEL=errors
EOF

    chmod 600 .env
    print_success "Configuration saved to .env"

    setup_complete
}

setup_complete() {
    echo ""
    echo -e "${BOLD}${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║           Setup Complete!              ║${NC}"
    echo -e "${BOLD}${GREEN}╚════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BOLD}Next steps:${NC}"
    echo ""
    echo "  1. Start the server:"
    echo -e "     ${CYAN}npm start${NC}"
    echo ""
    echo "  2. Scan the QR code with WhatsApp on your phone:"
    echo "     WhatsApp → Settings → Linked Devices → Link a Device"
    echo ""
    echo "  3. Configure your MCP client (Claude Desktop or Cursor)"
    echo ""
    echo -e "${BOLD}Claude Desktop config:${NC}"
    echo -e "${DIM}~/Library/Application Support/Claude/claude_desktop_config.json${NC}"
    echo ""
    cat << 'EOF'
{
  "mcpServers": {
    "whatsapp": {
      "command": "node",
      "args": ["FULL_PATH_TO/whatsapp-ai/dist/index.js"],
      "env": {
        "WHATSAPP_PASSPHRASE": "YOUR_PASSPHRASE"
      }
    }
  }
}
EOF
    echo ""
    echo -e "${DIM}Replace FULL_PATH_TO with the actual path to this directory:${NC}"
    echo -e "${CYAN}$(pwd)${NC}"
    echo ""
    
    read -p "Start the server now? (Y/n) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo ""
        npm start
    fi
}

# Run main
main "$@"
